### ISSUE TITLE
Create a decent frontend for the site

### ISSUE THREAD

**Issue by Exter-dg** [Exter-dg/typingSpeedometer#2]

**Comment by saifurrahmantanvir** [comment]
Hi there, I am excited to contribute to this project. I am creating the front end. I hope you will like it.
Have a nice day.

**Comment by Exter-dg** [comment]
@saifurrahmantanvir Do check the latest commit - https://github.com/Exter-dg/typingSpeedometer/commit/445f914e8248a6cfde785525822fc2ffc297e7e5

This adds a leaderboard table (from index.js) to the html.

**Comment by Exter-dg** [comment]
#4
